name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSementsov/kivy-android-builder@v1
        with:
          buildozer_spec_path: ./buildozer.spec
          python_version: 3.9
          package_name: your.app.package.name
          version: 1.0

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: bin/your.app.package.name-1.0-arm64-v8a-release.apk
