name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout project
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install basic dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools python3-dev build-essential \
            git zip unzip tar curl openjdk-11-jdk

      # 3️⃣ Install Buildozer & Cython
      - name: Install Buildozer & Cython
        run: |
          python3 -m pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      # 4️⃣ Setup Android SDK
      - name: Setup Android SDK & accept licenses
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q sdk-tools.zip -d tools
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # 5️⃣ Build APK
      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools
          buildozer android debug
