name: Build KivyMD APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2️⃣ Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # 3️⃣ Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl openjdk-17-jdk git python3-pip build-essential

    # 4️⃣ Setup Android SDK
    - name: Setup Android SDK
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools

        # Download Command Line Tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools.zip
        mkdir -p latest
        mv cmdline-tools/* latest/

        # Add sdkmanager to PATH
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

        # Accept licenses
        yes | sdkmanager --licenses

        # Install stable tools only
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    # 5️⃣ Install Buildozer
    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        pip install cython==0.29.36 buildozer==1.4.4

    # 6️⃣ Build APK
    - name: Build APK
      run: |
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug
        ls -la bin/

    # 7️⃣ Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
